version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - '9200:9200'
    networks:
      - elasticnet
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - elasticsearch.url=http://localhost:9200
      - elasticsearch.hosts=http://localhost:9200
    ports:
      - '5601:5601'
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # RabbitMQ
      - '15672:15672' # Management interface
    networks:
      - elasticnet
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

networks:
  elasticnet:
    driver: bridge

volumes:
  esdata1:
    driver: local
  rabbitmqdata:
    driver: local
